version: '3.2'

services:
  postgres:
    image: postgres:14.7
    environment:
      - POSTGRES_DB=eatfast
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - "dbdata:/var/lib/postgresql/data"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  web:
    build: 
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    environment:
      - DATABASE_URL=postgres://postgres:password@postgres:5432/eatfast
      - REDIS_URL=redis://redis:6379
      - PORT=3000
    volumes:
      - .:/app
      - node_modules:/app/node_modules

volumes:
  dbdata:
  node_modules:



# version: '3'

# services:
#   app:
#     user: vscode

#     build:
#       context: ..
#       dockerfile: .devcontainer/Dockerfile
#       args:
#         # Update 'VARIANT' to pick a Ruby version: 2, 2.7, 2.6, 2.5
#         VARIANT: 3.2.1
#         USER_UID: 1000
#         USER_GID: 1000
#         NODE_VERSION: lts/*

#     volumes:
#       - ../..:/workspaces:cached
#       - $HOME/.ssh/:/home/vscode/.ssh/ # Mount the ssh folder to authenticate with github

#     # Overrides default command so things don't shut down after the process ends.
#     command: sleep infinity

#     # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
#     network_mode: service:db

#     # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
#     # (Adding the "ports" property to this file will not forward from a Codespace.)

#     links: 
#       - db

#   db:
#     image: postgres:latest
#     restart: unless-stopped
#     volumes:
#       - postgres-data:/var/lib/postgresql/data
#       # - ./create-db-user.sql:/docker-entrypoint-initdb.d/create-db-user.sql
#     ports: 
#     - 5432:5432
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_DB: postgres
#       POSTGRES_PASSWORD: postgres
#       # Your config/database.yml should use the user and password you set here,
#       # and host "db" (as that's the name of this service). You can use whatever
#       # database name you want. Use `bin/rails db:prepare` to create the database.
#       #
#       # Example:
#       #
#        development:
#          <<: *default
#          host: db
#          username: postgres
#          password: 
#          database: eatfast_development

#     # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
#     # (Adding the "ports" property to this file will not forward from a Codespace.)

# volumes:
#   postgres-data:
